import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div class='container'>
        <div class='row'>
          <div class='col-1'>1</div>
          <div class='col-1'>2</div>
          <div class='col-1'>3</div>
          <div class='col-1'>4</div>
          <div class='col-1'>5</div>
          <div class='col-1'>6</div>
          <div class='col-1'>7</div>
          <div class='col-1'>8</div>
          <div class='col-1'>9</div>
          <div class='col-1'>10</div>
          <div class='col-1'>11</div>
          <div class='col-1'>12</div>
        </div>
        <div class='row'>
          <div class='col-2'>2</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>23</div>
        </div>
        <div class='row'>
          <div class='col-3'>3</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
        </div>
        <div class='row'>
          <div class='col-4'>4</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
        </div>
        <div class='row'>
          <div class='col-5'>5</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
        </div>
        <div class='row'>
          <div class='col-6'>6</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
        </div>
        <div class='row'>
          <div class='col-7'>7</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
        </div>
        <div class='row'>
          <div class='col-8'>8</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
        </div>
        <div class='row'>
          <div class='col-9'>9</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
        </div>
        <div class='row'>
          <div class='col-10'>10</div>
          <div class='col-1'>1</div>
          <div class='col-1'>1</div>
        </div>
        <div class='row'>
          <div class='col-11'>11</div>
          <div class='col-1'>1</div>
        </div>
        <div class='row'>
          <div class='col-12'>12</div>
        </div>
      </div>
    </div>
  )
}
